app.py
from config import app
from blueprints.login_routes import login_blueprint
from blueprints.cadastro_routes import cadastro_blueprint

app.register_blueprint(login_blueprint)
app.register_blueprint(cadastro_blueprint)

if __name__ == '__main__':
    app.run(host=app.config['HOST'],
            port=app.config['PORT'],
            debug=app.config['DEBUG'])

blueprints/cadastro_routes.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for
from config import mysql, db

cadastro_blueprint = Blueprint('cadastro', __name__)

@cadastro_blueprint.route('/criar-usuario', methods=['POST'])
def criar_usuario():
    if request.method == 'POST':
        dados = request.form

        query = f"""
            INSERT INTO USUARIOS(
                NOME,
                EMAIL,
                SENHA,
                TELEFONE,
                SEXO,
                DATA_NASC,
                CURSO_CARGO,
                TURNO,
                TIPO
            )
            VALUES(
                '{dados['nome']}',
                '{dados['email']}',
                '{dados['senha']}',
                {dados['telefone']},
                '{dados['genero']}',
                '{dados['data_nasc']}',
                '{dados['curso_cargo']}',
                '{dados['turno']}',
                1
            );
        """

        cursor = db.cursor(dictionary=True)
        cursor.execute(f'''
            SELECT *
            FROM USUARIOS
            WHERE EMAIL = '{dados['email']}';
        ''')
        usuario = cursor.fetchone()

        if usuario:
            return redirect(url_for('login.cadastro'))
        
        else:
            cur = mysql.connection.cursor()
            cur.execute(query)
            mysql.connection.commit()

            return redirect(url_for('login.login'))
    
    return render_template('cadastro.html')

blueprints/login_routes.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for
from config import db

login_blueprint = Blueprint('login', __name__)


@login_blueprint.route('/', methods=['GET'])
def login():
    return render_template('login.html')

@login_blueprint.route('/read-login-form', methods=['GET', 'POST'])
def read_login_form():
    if request.method == 'POST':
        email = request.form['email']
        senha = request.form['senha']

        cursor = db.cursor(dictionary=True)
        cursor.execute(f'''
            SELECT *
            FROM USUARIOS
            WHERE EMAIL = '{email}'
                AND SENHA = '{senha}';
        ''')
        usuario = cursor.fetchone()
        print(usuario)

        if usuario:
            return render_template('index.html')
        
        else:
            return redirect(url_for('login.login'))
    
    return render_template('login.html')


@login_blueprint.route('/index', methods=['GET'])
def index():
    return render_template('index.html')

@login_blueprint.route('/cadastro', methods=['GET'])
def cadastro():
    return render_template('cadastro.html')

templates/cadastro.html
<!DOCTYPE html>

<html lang="pt-br">

    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, inicial-scale=1.0">

        <title>Cadastro | Doce Impacto</title>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{url_for('static', filename='styles/style-cadastro.css')}}" type="text/css">

        <link rel="icon" href="{{url_for('static', filename='images/cupcake.png')}}" type="image/png">

    </head>

    <body>

        <div class="box">

            <form action="{{url_for('cadastro.criar_usuario')}}" method="POST">

                <fieldset>

                    <legend><b>Doce Casdastro</b></legend>
                    <br>

                    <div class="inputBox">
                        <input type="text" name="nome" id="nome" class="inputUser" required>
                        <label for="nome" class="label-input">Nome</label>
                    </div>
                    <br></br>

                    <div class="inputBox">
                        <input type="email" name="email" id="email" class="inputUser" required>
                        <label for="email" class="label-input">Email</label>
                    </div>
                    <br></br>

                    <div class="inputBox">
                        <input type="password" name="senha" id="senha" class="inputUser" required>
                        <label for="senha" class="label-input">Senha</label>
                    </div>
                    <br></br>

                    <div class="inputBox">
                        <input type="tel" name="telefone" id="telefone" class="inputUser" required>
                        <label for="telefone" class="label-input">Telefone</label>
                    </div>
                    <br>

                    <p>Sexo:</p>
                    <input type="radio" id="feminino" name="genero" value="F" required>
                    <label for="feminino">Feminino</label>
                    <br>

                    <input type="radio" id="masculino" name="genero" value="M" required>
                    <label for="masculino">Masculino</label>
                    <br>

                    <input type="radio" id="outro" name="genero" value="O" required>
                    <label for="outro">Outro</label>
                    <br></br>

                    <label for="data_nasc"><b>Data de Nascimento</b></label>
                    <input type="date" name="data_nasc" id="data_nasc" required>
                    <br></br>

                    <div class="inputBox">
                        <input type="text" name="curso_cargo" id="curso_cargo" class="inputUser">
                        <label for="curso_cargo" class="label-input">Curso ou Cargo</label>
                    </div>
                    <br></br>

                    <div class="inputBox">
                        <input type="text" name="turno" id="turno" class="inputUser">
                        <label for="turno" class="label-input">Turno</label> 
                    </div>
                    <br></br>

                    <input type="submit" name="submit" id="submit">

                </fieldset>

            </form>

        </div>

    </body>

</html>

templates/index.html
<!DOCTYPE html>

<html lang="pt-br">

    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, inicial-scale=1.0">

        <title>Página Inicial</title>

        <link rel="icon" href="{{url_for('static', filename='images/cupcake.png')}}" type="image/png">

    </head>

    <body>

        <h1>Doce Impacto</h1>

    </body>

</html>

templates/login.html
<!DOCTYPE html>

<html lang="pt-br">

    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, inicial-scale=1.0">

        <title>Login | Doce Impacto</title>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{url_for('static', filename='styles/style-login.css')}}" type="text/css">

        <link rel="icon" href="{{url_for('static', filename='images/cupcake.png')}}" type="image/png">

    </head>

    <body>

        <div class="login-box">

            <form action="{{url_for('login.read_login_form')}}" method="POST">

                <div class="login-header">
                    <header>login</header>
                </div>

                <div class="input-box">
                    <input name="email" id="email" type="email" class="input-field" placeholder="Email" required>
                </div>

                <div class="input-box">
                    <input name="senha" id="senha" type="password" class="input-field" placeholder="Senha" required>
                </div>

                <div class="input-submit">
                    <button type="submit" class="submit-btn" id="submit"></button>
                    <label for="submit">Login</label>
                </div>

                <div class="cadastro-link">
                    <p>Não tem uma conta? <a href="{{url_for('login.cadastro')}}">Cadastre-se</a></p>
                </div>

            </form>

        </div>

    </body>

</html>